Catkin-ProjectName: sbpl
Version: 1.1.0
Description: Search-based Planning Library (SBPL)
Author: Maxim Likhachev <maximl@seas.upenn.edu>
Maintainer: E. Gil Jones <gjones@willowgarage.com>
Homepage: http://www.ros.org

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake

Depends: cmake, ros_comm, pkg-config
